### PR TITLE
Create AndroidApp API routes, feature tests, database fixes

### LINKED ISSUE #24: Create API endpoints for fetching AndroidApps
- [x] Create API AndroidApps controller
 - [x] Add required API routes
 - [x] Implement view method in the controller

### PR DESCRIPTION
**Pull request by shevtsod**
Closes #24

### CODE REVIEW

**Comment by shevtsod** [comment]
@Uyser @oscar666666 

This PR implements the API routes needed to fetch and create AndroidApps, as well as the associated feature tests and some fixes to the database.

You might need to reset your local copy after this, but hopefully we won't have to do this anymore in the future.

```php
# Clear composer cache
composer dump-autoload

# Drop and rebuild database
php artisan db:fresh

# Re-install the app
php artisan app:install
```

**Review by oscar666666 — APPROVED** [review]
approved^_^

**Comment by oscar666666** [comment]
a

**Comment by shevtsod** [comment]
@oscar666666 ty ty 👍

**Pull request merged**
